### PR TITLE
Make PlayMorphia module more configurable

### PR DESCRIPTION
**Pull request by gtrog**

### CODE REVIEW

**Comment by jadeglaze** [comment]
Gene, is this a permanent thing going forward? (Having a forked play morphia plugin?) or are you just temporarily using it for debugging?

I ask because I was very close to doing the same thing yesterday in order to put in a low-level fix to prevent product catalog from blasting the mongo DB when unit tests are run in the wrong environment.

**Comment by gtrog** [comment]
It's a permanent thing.  One of the main hurdles I've run into time and time again is being able to configure low-level options for the Mongo driver which the PlayMorphia plugin doesn't easily allow in conjunction with configuring it for SSL as well.  Since we don't plan on investing much more effort in using/upgrading Play in the future, I think this should be fairly safe to do.  Another nice feature I'm adding in here is having gridFS disabled by default, rather than enabled, which has been creating these empty gridFS collections

**Comment by jadeglaze** [comment]
Awesome man. I agree it seems safe to fork in this context. I will likely
wait until you've finished merging what you're doing right now and then
update MorphiaFixtures to do some safety checks so it can't delete
Stage/QA/Prod dbs. (The alternative is to create a new MorphiaFixtures
subclass and replace all calls, which I think sucks.)

**Comment by gtrog** [comment]
Well, these changes will never really get "merged", unless we decide we want to clobber master on this fork with an older version we're developing.

**Comment by jadeglaze** [comment]
Without merging to master is it possible to do CR on our own branches then
merge into 1.2.4c-ext via github?  (basically treat 1.2.4c-ext as our
special master branch)

**Comment by gtrog** [comment]
Actually, we might as well clobber master and call it our own.  If we ever need to cherry-pick something from the original, we can, but chances are, we'll never do that.

**Comment by gtrog** [comment]
This PR is now mergable, I'll wait for someone to merge the changes :)

**Comment by jadeglaze** [comment]
Agreed

**Pull request merged**
